# data.yml
package_name: bike_sharing_reg

# Data paths
training_data_path: datasets/raw/hour.csv
test_data_path: datasets/processed/test_split.csv

# Target
target: cnt

# Features
features:
  - season
  - yr
  - mnth
  - hr
  - holiday
  - weekday
  - workingday
  - weathersit
  - temp
  - atemp
  - hum
  - windspeed

# Cyclical Features
cyclical_cols:
  - season
  - mnth
  - weekday
  - hr

# Numerical Features
num_cols: 
  - temp
  - atemp
  - hum
  - windspeed

# Categorical Features
cat_cols:
  - weathersit

# Train/Test split
split:
  test_size: 0.2
  random_state: 42

